refactor: update compose and Makefile to use retail root env variable…
intel-retail/retail-use-cases pull request #15
Opened 2024-03-21 19:39 UTC by ejlee3

… instead of hard coding for volume mounts

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/retail-use-cases/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/retail-use-cases )

2024-03-26 22:04 UTC, jim-wang-intel requested changes
some syntax error when i ran make file targets from the project root directory: make run-gprc_python for example

2024-03-26 22:04 UTC, jim-wang-intel commented on use-cases/demos/Makefile
> +	@PIPELINE_COUNT=${PIPELINE_COUNT} @RETAIL_USE_CASE_ROOT=$(RETAIL_USE_CASE_ROOT) @RESULTS_DIR=$(RESULTS_DIR) docker compose -f $(DEPENDENCY_COMPOSE) -f add_demo_classification.yml convert > $(DOCKER_
remove @ symbol for REATIL_USE_CASE_ROOT and RESULTS_DIR as it is not working when I tested it

2024-03-28 15:09 UTC, brian-intel commented on use-cases/dlstreamer/Makefile
> +	PIPELINE_SCRIPT=$(PIPELINE_SCRIPT) PIPELINE_COUNT=$(PIPELINE_COUNT) @RETAIL_USE_CASE_ROOT=$(RETAIL_USE_CASE_ROOT) @RESULTS_DIR=$(RESULTS_DIR) docker compose -f $(DOCKER_COMPOSE) up -d
remove @ from RETAIL_USE_CASE_ROOT & RESULTS_DIR

2024-03-28 15:09 UTC, brian-intel commented on use-cases/grpc_go/Makefile
> +	PIPELINE_COUNT=$(PIPELINE_COUNT) @RETAIL_USE_CASE_ROOT=$(RETAIL_USE_CASE_ROOT) @RESULTS_DIR=$(RESULTS_DIR) docker compose -f $(DOCKER_COMPOSE) up -d
remove @ from RETAIL_USE_CASE_ROOT & RESULTS_DIR

2024-03-28 15:09 UTC, brian-intel commented on use-cases/grpc_python/Makefile
> +	PIPELINE_COUNT=$(PIPELINE_COUNT) MODEL_NAME=$(MODEL_NAME) @RETAIL_USE_CASE_ROOT=$(RETAIL_USE_CASE_ROOT) @RESULTS_DIR=$(RESULTS_DIR) docker compose -f $(DOCKER_COMPOSE) up -d
remove @ from RETAIL_USE_CASE_ROOT & RESULTS_DIR

2024-03-28 15:09 UTC, brian-intel commented on use-cases/gst_capi/Makefile
> +	@PIPELINE_COUNT=${PIPELINE_COUNT} @RETAIL_USE_CASE_ROOT=$(RETAIL_USE_CASE_ROOT) @RESULTS_DIR=$(RESULTS_DIR) docker compose -f $(CAMERA_SIMULATOR_COMPOSE) -f add_gst_capi_yolov5.yml convert > $(DOCKE
remove @ from RETAIL_USE_CASE_ROOT & RESULTS_DIR

2024-03-28 19:05 UTC, jim-wang-intel reviewed
please rebase and get the smoke tests and run smoke tests from the root directory: `make run-smoke-tests` to see if works

2024-03-29 00:04 UTC, brian-intel approved these changes

2024-03-29 17:01 UTC, jim-wang-intel commented on use-cases/demos/Makefile
> +	@PIPELINE_COUNT=${PIPELINE_COUNT} RETAIL_USE_CASE_ROOT=$(RETAIL_USE_CASE_ROOT) docker compose -f $(DEPENDENCY_COMPOSE) -f add_demo_instance_segmentation.yml convert > $(DOCKER_COMPOSE)
missing RESULT_DIR="$(RESULT_DIR)"

2024-03-29 18:10 UTC, jim-wang-intel approved these changes
tested locally and works perfect for me!

2024-03-29 18:15 UTC, merged