Add capi yolov8 docker compose use cases for gst-capi
intel-retail/retail-use-cases pull request #22
Opened 2024-04-23 22:53 UTC by jim-wang-intel

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [ ] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/retail-use-cases/blob/main/CONTRIBUTING.md
- [ ] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/retail-use-cases )

2024-04-23 22:59 UTC, jim-wang-intel commented on models-downloader/Dockerfile.bitModel
this bit model dockerfile was missing before, added it in

2024-04-24 22:21 UTC, brian-intel approved these changes

2024-04-24 22:41 UTC, antoniomtz requested changes

2024-04-24 22:41 UTC, antoniomtz commented on models-downloader/Dockerfile.bitModel
> +# Copyright (C) 2023 Intel Corporation.
```suggestion
# Copyright (C) 2024 Intel Corporation.
```

2024-04-25 15:01 UTC, jim-wang-intel commented on models-downloader/Dockerfile.bitModel
> +# Copyright (C) 2023 Intel Corporation.
fixed

2024-04-25 18:18 UTC, antoniomtz approved these changes

2024-04-29 23:12 UTC, merged